#!/bin/bash
set -euo pipefail
pd_pid="$1"
pd_app="$2"
pd_staged="$3"
pd_work="$4"
pd_parent="$(dirname "$pd_app")"
pd_suffix="$(basename "$pd_work")"
pd_new="$pd_parent/.$pd_suffix.app"
pd_previous="$pd_parent/.$pd_suffix.previous.app"
pd_moved=0
pd_done=0

pd_finish() {
  pd_result=$?
  if [ "$pd_done" != 1 ]; then
    if [ "$pd_moved" = 1 ] && [ -d "$pd_previous" ]; then
      # All paths are generated by SidePad; retain the failed new app for diagnosis.
      if [ -d "$pd_app" ]; then /bin/mv "$pd_app" "$pd_work/Failed.app"; fi
      /bin/mv "$pd_previous" "$pd_app"
    fi
    /usr/bin/open "$pd_app" || true
    printf 'Update failed (status %s); previous app retained.\n' "$pd_result" > "$pd_work/FAILED.txt"
  fi
  if [ -d "$pd_new" ]; then /bin/mv "$pd_new" "$pd_work/Unused.app"; fi
}
trap pd_finish EXIT

# Prepare a verified copy on the destination volume before replacing anything.
/usr/bin/ditto "$pd_staged" "$pd_new"
/usr/bin/codesign --verify --strict -R '=identifier "studio.prxs.paddisplay.mac"' "$pd_new"
for ((pd_wait=0; pd_wait<30; pd_wait++)); do
  if ! /bin/kill -0 "$pd_pid" 2>/dev/null; then break; fi
  /bin/sleep 1
done
if /bin/kill -0 "$pd_pid" 2>/dev/null; then exit 1; fi

/bin/mv "$pd_app" "$pd_previous"
pd_moved=1
/bin/mv "$pd_new" "$pd_app"
/usr/bin/codesign --verify --strict "$pd_app"
/usr/bin/open "$pd_app"
pd_done=1
# Keep the previous version with the updater log for recovery.
/bin/mv "$pd_previous" "$pd_work/Previous.app"
printf 'Update installed successfully.\n' > "$pd_work/SUCCESS.txt"
